"$schema" = 'https://starship.rs/config-schema.json'
# RICE : https://i.redd.it/8cbtmudmyzca1.png
add_newline = true
command_timeout=1500
# | [Git](fg:green)  | $git_branch $git_commit $git_state $git_metrics $git_status
format = """
$os[](fg:#FFFFFF bg:black)$time $fill \
$java$golang$helm$lua$nodejs$perl$python$red$rust\
$shell$git_branch$docker_context$kubernetes$azure$terraform$hostname$username[](fg:#FFFFFF bg:black)$os\
$line_break\
$directory\
$status\
$character"""
right_format="$cmd_duration"

[directory]
# format='[  $path ]($style)[](fg:green bg:#2e333c)'
# style='bg:green fg:black'
format='[  $path ]($style)'
style='fg:blue'
home_symbol='~'

[username]
format='[ ](fg:blue) $user '
show_always=true

[hostname]
format='[](fg:blue) $hostname'
ssh_only=false
disabled=true

[fill]
symbol = ' '

[line_break]
disabled=false

[cmd_duration]
format=' [祥$duration]($style) '
# style='fg:#3a404c'
style='fg:#7f848e'

[kubernetes]
disabled = false
symbol=""
format='[$symbol](fg:blue) $context( \($namespace\))'

[terraform]
disabled = false

[git_status]
disabled = false

[git_branch]
symbol= " "
# #3d434f
# #2e333c fg:#7f848e
format='[$symbol](fg:blue) $branch(:$remote_branch) '

[time]
disabled = false
style='fg:blue'
format = '[  ]($style)$time'
time_format = "%T"
utc_time_offset = "local"

[golang]
format='[$symbol](bold)'
symbol= '  '

[java]
format='[$symbol](fg:blue)'
symbol='  '

[character]
# format="[ ](bg:#2e333c)[](bold fg:#2e333c bg:black)$symbol "
format='[$symbol]($style) '
error_symbol='[➤](fg:red)'
success_symbol='[➤](fg:green)'

[azure]
disabled = false
format = ' [$symbol]($style) $subscription '
symbol = 'ﴃ'
style = 'blue bold'

[os]
disabled=false
format='[ $symbol ]($style)'
style='bg:#FFFFFF fg:black'

[os.symbols]
Arch=''
Windows=''

[lua]
format='[$symbol]($style) [lua](fg:white)'
symbol='󰢱'
style='fg:blue'
