"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout=1500
# | [Git](fg:green)  | $git_branch $git_commit $git_state $git_metrics $git_status
format = """
$os$time $fill \
$java$lua$golang$rust$nodejs$elm$golang$helm$lua$nodejs$perl$python$red$rust$shell$git_branch$docker_context$kubernetes$azure$terraform$hostname$username\
$line_break\
$directory\
$cmd_duration\
$status\
$character"""
right_format="$cmd_duration"
# 
# format = """
# $time\
# $username\
# $hostname\
# $shlvl\
# $singularity\
# $kubernetes\
# $git_branch\
# $git_status\
# $directory\
# $docker_context\
# $package\
# $deno\
# $elm\
# $golang\
# $helm\
# $java\
# $lua\
# $nodejs\
# $perl\
# $python\
# $red\
# $rust\
# $terraform\
# $nix_shell\
# $memory_usage\
# $env_var\
# $custom\
# $cmd_duration\
# $line_break\
# $jobs\
# $status\
# $fill\
# $shell
# $character"""

# [palettes]
# gray='#3d434f'

[directory]
# format='[  $path ]($style)[](fg:green bg:#2e333c)'
# style='bg:green fg:black'
format='[  $path ]($style)'
style='fg:green'
home_symbol='~'

[username]
format='[ ](fg:blue) $user'
show_always=true

[hostname]
format='[](fg:blue) $hostname'
ssh_only=false
disabled=true

[fill]
symbol = ' '

[line_break]
disabled=false

[cmd_duration]
format=' [祥$duration]($style) '
style='fg:#3a404c'

[kubernetes]
disabled = false
symbol=""
format='[$symbol](fg:blue) $context( \($namespace\))'

[terraform]
disabled = false

[git_status]
disabled = false

[git_branch]
symbol= " "
# #3d434f
# #2e333c fg:#7f848e
format='[$symbol](fg:blue) $branch(:$remote_branch) '

[time]
disabled = false
style='fg:blue'
format = '[  ]($style)$time'
time_format = "%T"
utc_time_offset = "local"

[golang]
format='[$symbol](bold)'
symbol= '  '

[java]
format='[$symbol](fg:blue)'
symbol='  '

[character]
# format="[ ](bg:#2e333c)[](bold fg:#2e333c bg:black)$symbol "
format='[$symbol]($style) '
error_symbol='[➤](fg:red)'
success_symbol='[➤](fg:green)'

[azure]
disabled = false
format = ' [$symbol]($style) $subscription '
symbol = 'ﴃ'
style = 'blue bold'

[os]
disabled=false
format='[ $symbol ]($style)[](fg:white bg:black)'
style='bg:white fg:black'

[os.symbols]
Arch=''
Windows=''
