#!/bin/bash
#
#


currentTz=`date +"%z" | cut -b 1-3`
currentTime=`date +"%R"`

case "$BLOCK_BUTTON" in
  1)
  i3-msg -q exec /usr/bin/gsimplecal
esac

echo "  $currentTime [$currentTz]"
echo "  $currentTime"
